export const geniusConfig = {
  user: 'prosperoquantum',
  password: 'P@ssw0rd!',
  apiKeyV1: 'rYMEbRnWT22zSSmxjPFA3ajrcqQIQbdq2KsPODz3',
  authUrlV1: 'https://api.geniussports.com/Auth-v1/PROD/login',
  refreshUrl: 'https://api.geniussports.com/Auth-v1/PROD/refresh',
  sourceId: 'GeniusSportsInPlay',
  sportId: 10, 
  apiKey: 'lXoO9WOBUS17jvaFx68hUaFwKE8na8Ax70E3dOmK', 
  apiProdKey: 'lXoO9WOBUS17jvaFx68hUaFwKE8na8Ax70E3dOmK', 
  clientId: 'st9eg3d317igsg0oled7qkred', 
  clientProdId: 'st9eg3d317igsg0oled7qkred', 
  clientSecret: '5pbkibe0t42u7epkuv5g4onfiepsoopkp319ppaas29jsd0kabm', 
  clientProdSecret: '5pbkibe0t42u7epkuv5g4onfiepsoopkp319ppaas29jsd0kabm', 
  authUrl: 'https://uat.auth.api.geniussports.com/oauth2/token', 
  authProdUrl: 'https://uat.auth.api.geniussports.com/oauth2/token', 
  matchProdStateUrl: 'https://platform.uat.matchstate.api.geniussports.com/api/v1', 
  matchStateUrl: 'https://platform.uat.matchstate.api.geniussports.com/api/v1', 
  msFixtureUrl: 'https://platform.matchstate.api.geniussports.com/api/v1/sources/GeniusSportsInPlay/sports/10/fixtures',
  fixtureUrl: 'https://fixtures.api.geniussports.com/v2/fixtures',
  fixtureUrlV1: 'https://api.geniussports.com/Fixtures-v1/PRODPRM/fixtures'
}; 